# Generated by Django 3.2 on 2022-02-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sim_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('os', models.CharField(blank=True, max_length=254, null=True)),
                ('screen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('camera', models.CharField(blank=True, max_length=254, null=True)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colors', models.CharField(blank=True, max_length=254, null=True)),
                ('bronze_24_upfront', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bronze_24_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('silver_24_upfront', models.DecimalField(decimal_places=2, max_digits=6)),
                ('silver_24_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gold_24_upfront', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gold_24_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('platinum_24_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='sim_only',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.CharField(blank=True, max_length=254, null=True)),
                ('minutes', models.CharField(blank=True, max_length=254, null=True)),
                ('text', models.CharField(blank=True, max_length=254, null=True)),
                ('data_5g', models.BooleanField(blank=True, default=False, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='sim_free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('os', models.CharField(blank=True, max_length=254, null=True)),
                ('screen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('camera', models.CharField(blank=True, max_length=254, null=True)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colors', models.CharField(blank=True, max_length=254, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
    ]
