# Generated by Django 3.2 on 2022-02-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220206_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfree',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simonly',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplan',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
