# Generated by Django 3.2 on 2022-02-07 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220206_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfree',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='test', max_length=254, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='cost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='simfree',
            name='storage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='simonly',
            name='length',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='simplan',
            name='storage',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
